blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import blog, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('article/', blog, name='article_list'),
    path('article_view/<int:pk>/', cache_page(60)(ArticleDetailView.as_view()), name='article_view'),
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing import views

app_name = MailingConfig.name

urlpatterns = [
     path('', views.IndexView.as_view(), name='index'),
     path('contacts/', views.contacts, name='contacts'),

     path('client/', views.ClientListView.as_view(), name='client'),
     path('client/view/<int:pk>', views.ClientDetailView.as_view(), name='client_detail'),
     path('client/create/', views.ClientCreateView.as_view(), name='create_client'),
     path('client/edit/<int:pk>/', views.ClientUpdateView.as_view(), name='update_client'),
     path('client/delete/<int:pk>/', views.ClientDeleteView.as_view(), name='delete_client'),

     path('mail/', views.MailListView.as_view(), name='mail'),
     path('mail/view/<int:pk>', views.MailDetailView.as_view(), name='mail_detail'),
     path('mail/create/', views.MailCreateView.as_view(), name='create_mail'),
     path('mail/edit/<int:pk>/', views.MailUpdateView.as_view(), name='update_mail'),
     path('mail/delete/<int:pk>/', views.MailDeleteView.as_view(), name='delete_mail'),

     path('mailing_config/', views.MailingConfigListView.as_view(), name='mailing_config'),
    path('mailing_config/view/<int:pk>/', views.MailingConfigDetailView.as_view(), name='mailing_config_detail'),
    path('mailing_config/create/', views.MailingConfigCreateView.as_view(), name='create_mailing_config'),
    path('mailing_config/edit/<int:pk>/', views.MailingConfigUpdateView.as_view(), name='update_mailing_config'),
    path('mailing_config/delete/<int:pk>/', views.MailingConfigDeleteView.as_view(), name='delete_mailing_config'),
    path('mailing_config/activity/<int:pk>/', views.toogle_activity, name='toogle_activity'),
]

mailing/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

NULLABLE = {'blank': True, 'null':True}

class Client(models.Model):

    last_name = models.CharField(max_length=150, verbose_name='Фамилия')
    first_name = models.CharField(max_length=150, verbose_name='Имя')
    patronymic = models.CharField(max_length=150, verbose_name='Отчество', **NULLABLE)
    email = models.EmailField(max_length=254, verbose_name='Электронная почта')
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Владелец')

    def __str__(self) -> str:
        return f'{self.last_name} {self.first_name} {self.patronymic}'
    
    class Meta():
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'           

class Mail(models.Model):

    them_mail = models.CharField(max_length=150, verbose_name='Тема письма')
    body_mail = models.TextField(verbose_name='Тело письма', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Владелец')

    def __str__(self) -> str:
        return f'{self.them_mail}'
    
    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'

class MailingConfig(models.Model):

    PERIOD_CHOICES = [
        ('per_day', 'раз в день'),
        ('per_week', 'раз в неделю'),
        ('per_month', 'раз в месяц'),
    ]
    STATUS_CHOICES = [
        ('create', 'создана'),
        ('complete', 'завершена'),
        ('extend', 'запущена'),
    ]

    name = models.CharField(max_length=100, verbose_name='Название рассылки', default='Рассылка')
    clients = models.ManyToManyField(Client, verbose_name='Кому (клиенты сервиса)')
    mail = models.ForeignKey(Mail, on_delete=models.CASCADE, verbose_name="Сообщение")
    date_start = models.DateField(verbose_name='Дата начала рассылки', default=timezone.now)
    date_next = models.DateTimeField(verbose_name="следующая дата рассылки",default=timezone.now)
    date_end = models.DateField(verbose_name='Дата окончания рассылки', default=timezone.now)
    start_time = models.TimeField(verbose_name='Время рассылки', default=timezone.now)
    period = models.CharField(max_length=30, choices=PERIOD_CHOICES, verbose_name='Периодичность рассылки',
                              default='per_day')
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, verbose_name='Статус рассылки',
                              default='create')
    is_active = models.BooleanField(default=True, verbose_name='Активация рассылки')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Владелец')


    def __str__(self):
        return f'{self.clients} {self.status}'
    
    class Meta:
        verbose_name = 'настройка'
        verbose_name_plural = 'настройки'
        permissions = [
            ("set_is_active", "активация рассылки")
        ]

class TryMailing(models.Model):

    mailing = models.ForeignKey(MailingConfig, on_delete=models.CASCADE, verbose_name='Рассылка', **NULLABLE)
    date_last_try = models.DateTimeField(auto_now=True, verbose_name='Дата последней попытки') 
    status_try = models.CharField(max_length=50, verbose_name='Статус попытки')
    answer_postmail = models.TextField(max_length=500, verbose_name='Ответ почтового сервера', **NULLABLE)

    def __str__(self) -> str:
        return f'{self.status_try}'
    
    class Meta:
        verbose_name = 'попытка рассылки'
        verbose_name_plural = 'попытки рассылки'

mailing/forms.py
from django import forms

from mailing.models import Client, Mail, MailingConfig

class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class ClientForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Client
        fields = '__all__'
        exclude = ('owner',)

class MailForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Mail
        fields = '__all__'
        exclude = ('owner',)

class MailingConfigForm(StyleFormMixin, forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        user = self.request.user
        super().__init__(*args, **kwargs)
        self.fields['clients'].queryset = Client.objects.filter(owner=user)
        self.fields['mail'].queryset = Mail.objects.filter(owner=user)

    class Meta:
        model = MailingConfig
        exclude = ('is_active', 'owner',)
        fields = '__all__'
        

        widgets = {
            'start_date': forms.DateTimeInput(attrs={'placeholder': 'ДД.ММ.ГГГГ ЧЧ:ММ:СС', 'type': 'datetime-local'}),
            'end_date': forms.DateTimeInput(attrs={'placeholder': 'ДД.ММ.ГГГГ ЧЧ:ММ:СС', 'type': 'datetime-local'}),
        }

mailing/views.py
import random
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Permission

from mailing import models
from mailing.forms import ClientForm, MailForm, MailingConfigForm
from mailing.services import get_cache_for_mailings

from blog.models import Article

# Index app
class IndexView(TemplateView):
    template_name = 'mailing/index.html'
    extra_context = {
        'title': 'Главная',
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['mail_count'] = get_cache_for_mailings()
        context_data['active_mail_count'] = len(models.MailingConfig.objects.filter(is_active=True))
        context_data['client_count'] = len(models.Client.objects.all())

        if Article.objects.all().count() > 2:
            context_data['object_list'] = random.choices(list(Article.objects.all()), k=3)

        return context_data


def contacts(request):
    context = {
        'title': "Контакты",
    }

    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(f"{name} ({phone}, {email}): {message}")

    return render(request, 'mailing/contacts.html', context)

# Client models
class ClientListView(LoginRequiredMixin, ListView):
    model = models.Client
    extra_context = {
        'title': 'Ваши клиенты',
    }

    def get_queryset(self, **kwargs):
        if self.request.user.is_superuser:
            return models.Client.objects.all()
        return models.Client.objects.filter(owner=self.request.user)

class ClientDetailView(DetailView):
    model = models.Client

class ClientCreateView(CreateView):
    model = models.Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)

class ClientUpdateView(UpdateView):
    model = models.Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client')

class ClientDeleteView(DeleteView):
    model = models.Client
    success_url = reverse_lazy('mailing:client')

# Mail models
class MailListView(LoginRequiredMixin, ListView):
    model = models.Mail
    extra_context = {
        'title': 'Сообщения для рассылки',
    }

    def get_queryset(self, **kwargs):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return models.Mail.objects.all()
        return models.Mail.objects.filter(owner=self.request.user)

class MailDetailView(DetailView):
    model = models.Mail

class MailCreateView(CreateView):
    model = models.Mail
    form_class = MailForm
    success_url = reverse_lazy('mailing:mail') 

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)

class MailUpdateView(UpdateView):
    model = models.Mail
    form_class = MailForm
    success_url = reverse_lazy('mailing:mail')

class MailDeleteView(DeleteView):
    model = models.Mail
    success_url = reverse_lazy('mailing:mail')

# MailingConfig models
class MailingConfigListView(LoginRequiredMixin, ListView):
    model = models.MailingConfig
    extra_context = {
        'title': "Рассылки",
    }

    def get_queryset(self, **kwargs):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return models.MailingConfig.objects.all()
        return models.MailingConfig.objects.filter(owner=self.request.user)

class MailingConfigDetailView(DetailView):
    model = models.MailingConfig

class MailingConfigCreateView(CreateView):
    model = models.MailingConfig
    form_class = MailingConfigForm
    success_url = reverse_lazy('mailing:mailing_config') 

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)

class MailingConfigUpdateView(PermissionRequiredMixin, UpdateView):
    model = models.MailingConfig
    form_class = MailingConfigForm
    success_url = reverse_lazy('mailing:mailing_config')
    permission_required = 'mailing.change_mail'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

class MailingConfigDeleteView(PermissionRequiredMixin, DeleteView):
    model = models.MailingConfig
    success_url = reverse_lazy('mailing:mailing_config')
    permission_required = 'mailing.delete_mailing_config'

def toogle_activity(request, pk):
    mail_item = get_object_or_404(models.MailingConfig, pk=pk)

    if mail_item.is_active:
        mail_item.is_active = False
    else:
        mail_item.is_active = True
    mail_item.save()

    return redirect('mailing:mailing_config')

mailing/templates/mailing/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" data-bs-theme="auto">
  <head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="Fedyaev Anton" />
    <title>FasterMailing</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/sign-in.css' %}" rel="stylesheet" />
    <link href="{% static 'css/blog.css' %}" rel="stylesheet" />

    <link href="https://cdn.jsdelivr.net/npm/@docsearch/css@3" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet" />

    <meta name="theme-color" content="#712cf9" />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>

  </head>
  <body>
    {% include 'mailing/includes/inc_main_menu.html' %}

    <main>
      <section class="py-5 text-center container">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">{{ title }}</h1>
            <p class="lead text-body-secondary">Сервис самой быстрой рассылки на западных землях!</p>
          </div>
        </div>
      </section>

      <div class="container">
        <div class="row">
          {% block content %}

          {% endblock %}
        </div>
      </div>
    </main>

    <footer class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item">
          <a href="{% url 'mailing:index' %}" class="nav-link px-2 text-body-secondary">Главная</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'blog:article_list' %}" class="nav-link px-2 text-body-secondary">Блог</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'mailing:contacts' %}" class="nav-link px-2 text-body-secondary">Контакты</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link px-2 text-body-secondary">FAQs</a>
        </li>
      </ul>
      <p class="text-center text-body-secondary">
        &copy; FedASCreated 2023 - {% now 'Y' %}
      </p>
    </footer>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
  <div class="col-12">
    <div class="row">
      <div class="col-6">
        <form method="post" enctype="multipart/form-data">
          <div class="card">
            <div class="card-header">
              <h4 class="card-title">Удалить клиента</h4>
            </div>

            <div class="card-body">
              {% csrf_token %}
              <p>Хотите удалить клиента "{{ object }}"?</p>
            </div>

            <div class="card-footer">
              <button type="submit" class="btn btn-danger">Подтвердить</button>
              <a href="{% url 'mailing:mailing_config' %}" class="btn btn-warning">Отмена</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
  <div class="col-12 form-control">
    <div class="card box-shadow">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">{{ object }}</h4>
      </div>
      <div class="card-body">
        <p class="list-unstyled mt-3 mb-4 text-start m-3">
          Email: {{ object.email }}<br />
          Комментарий: {{ object.comment }}
        </p>
        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing:client' %}">Назад к списку клиентов</a>
      </div>
    </div>
  </div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block content %}
  <div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailing:create_client' %}">Добавить клиента</a>
  </div>
  {% for object in object_list %}
    <div class="col-5">
      <div class="card mb-4 shadow-sm">
        <div class="card-header text-center">
          <h4 class="my-0 font-weight-normal">{{ object }}</h4>
        </div>

        <div class="card-body">
          <p class="card-text">{{ object.email }}</p>

          {% if object.comment != None %}
            <p class="card-text">{{ object.comment }}</p>
          {% else %}
            <p class="card-text">Комментарий отсутствует</p>
          {% endif %}
          
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <a class="btn btn-lg mt-2 mb-2 btn-block btn-outline-primary" href="{% url 'mailing:client_detail' object.pk %}">Просмотр</a>
              <a class="btn btn-lg mt-2 mb-2 btn-block btn-outline-primary" href="{% url 'mailing:update_client' object.pk  %}">Изменить</a>
              <a class="btn btn-lg mt-2 mb-2 btn-block btn-outline-danger" href="{% url 'mailing:delete_client' object.pk %}">Удалить</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock %}

mailing/templates/mailing/contacts.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>777032415</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Сущевский вал, д.34А к.1</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="email">Email</label>
                            <input type="email" name="email" class="form-control" id="email"
                                   placeholder="Контактный email" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message" placeholder="Ваше сообщение"
                                      required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
    {% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}
{% block content %}

<div class="jumbotron">
    <h2 class="mb-4">Статистика сервиса</h2>
    <p class="lead">Количество рассылок всего:  {{mail_count}}</p>
    <p class="lead">Количество активных рассылок: {{active_mail_count}}</p>
    <p class="lead">Количество уникальных клиентов для рассылок: {{client_count}}</p>
</div>
<p>
</p>
<div class="row">
    {% for object in object_list %}
    {% include 'mailing/includes/inc_blog.html' with object=object %}
    {% endfor %}
</div>

{% endblock %}

mailing/templates/mailing/mail_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
  <div class="col-12">
    <div class="row">
      <div class="col-6">
        <form method="post" enctype="multipart/form-data">
          <div class="card">
            <div class="card-header">
              <h4 class="card-title">Удалить сообщение</h4>
            </div>

            <div class="card-body">
              {% csrf_token %}
              <p>Хотите удалить сообщение "{{ object }}"?</p>
            </div>

            <div class="card-footer">
              <button type="submit" class="btn btn-danger">Подтвердить</button>
              <a href="{% url 'mailing:mailing_config' %}" class="btn btn-warning">Отмена</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

mailing/templates/mailing/mail_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
  <div class="col-12 form-control">
    <div class="card box-shadow">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">{{ object }}</h4>
      </div>
      <div class="card-body">
        <p class="list-unstyled mt-3 mb-4 text-start m-3">
          Тело сообщение: {{ object.body_mail }}
        </p>
        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing:mail' %}">Назад к списку сообщений</a>
      </div>
    </div>
  </div>
{% endblock %}

mailing/templates/mailing/mail_form.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}
{% crispy form %}
{% block content %}
  <div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
      <div class="col-6">
        <div class="card">
          <div class="card-header text-center">
            <h3 class="card-title">
              {% if object %}
                Сообщение
              {% else %}
                Добавить сообщение
              {% endif %}
            </h3>
          </div>

          <div class="card-body">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
              {% if object %}
                Сохранить
              {% else %}
                Создать
              {% endif %}
            </button>
          </div>
          <div class="card-footer"></div>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

mailing/templates/mailing/mail_list.html
{% extends 'mailing/base.html' %}

{% block content %}
  <div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailing:create_mail' %}">Добавить сообщение</a>
  </div>
  {% for object in object_list %}
    <div class="col-5">
      <div class="card mb-4 shadow-sm">
        <div class="card-header text-center">
          <h4 class="my-0 font-weight-normal">{{ object }}</h4>
        </div>

        <div class="card-body">
          <p class="card-text">{{ object.body_mail }}</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <a class="btn btn-lg mt-2 mb-2 btn-block btn-outline-primary" href="{% url 'mailing:mail_detail' object.pk %}">Просмотр</a>
              <a class="btn btn-lg mt-2 mb-2 btn-block btn-outline-primary" href="{% url 'mailing:update_mail' object.pk  %}">Изменить</a>
              <a class="btn btn-lg mt-2 mb-2 btn-block btn-outline-danger" href="{% url 'mailing:delete_mail' object.pk %}">Удалить</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock %}

mailing/templates/mailing/mailingconfig_list.html
{% extends 'mailing/base.html' %}

{% block content %}

  <div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailing:create_mailing_config' %}">Добавить рассылку</a>
  </div>
  {% for object in object_list %} 
    <div class="col-5">
      <div class="card mb-4 shadow-sm">
        <div class="card-header text-center">
          <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
        </div>

        <div class="card-body">
          <p class="card-text">
            Кому:
            <ul>
              {% for value in object.clients.all.values_list %}
                <li>{{value.1}}</li>
              {% endfor %}
            </ul>
          </p>

          <p class="card-text">Сообщение: {{object.mail}}</p>

          <p class="card-text">Дата начала: {{ object.date_start }}</p>

          {% if object.period == "per_day" %}
            <p class="card-text">Период: раз в день</p>
          {% elif object.period == "per_week" %}
            <p class="card-text">Период: раз в неделю</p>
          {% elif object.period == "per_month" %}
            <p class="card-text">Период: раз в месяц</p>
          {% endif %}
          
          {% if object.status == "create" %}
            <p class="card-text">Статус: создана</p>
          {% elif object.status == "complete" %}
            <p class="card-text">Статус: завершена</p>
          {% elif object.status == "extend" %}
            <p class="card-text">Статус: запущена</p>
          {% endif %}

          {% if user.is_staff or user.is_superuser%}
            <p class="card-text">Владелец: {{object.owner}}</p>
            <p class="card-text">
              {% if object.is_active %}
                Активация рассылки: Активна
              {% else %}
              Активация рассылки: Не активна
              {% endif %}
            </p>
          {% endif %}

          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <a class="btn btn-lg mt-2 mb-2 btn-block btn-outline-primary" href="{% url 'mailing:mailing_config_detail' object.pk %}">Просмотр</a>
              {% if user.is_superuser %}
                <a class="btn btn-lg mt-2 mb-2 btn-block btn-outline-primary" href="{% url 'mailing:update_mailing_config' object.pk  %}">Изменить</a>
                <a class="btn btn-lg mt-2 mb-2 btn-block btn-outline-danger" href="{% url 'mailing:delete_mailing_config' object.pk %}">Удалить</a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="card-footer">
          {% if perms.mailing.set_is_active %}
            {% if object.is_active %}
              <a href="{% url 'mailing:toogle_activity' object.pk %}" class="btn btn-warning">Деактивировать</a>
            {% else %}
              <a href="{% url 'mailing:toogle_activity' object.pk %}" class="btn btn-success">Активировать</a>
            {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock %}