blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import blog, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('article/', blog, name='article_list'),
    path('article_view/<int:pk>/', cache_page(60)(ArticleDetailView.as_view()), name='article_view'),
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone

NULLABLE = {'blank': True, 'null': True}

class Article(models.Model):
    title = models.CharField(max_length=250, verbose_name='Заголовок')
    body = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blogs/', **NULLABLE, verbose_name='Изображение')
    date_is_published = models.DateField(default=timezone.now, verbose_name='Дата публикации')
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')
    is_active = models.BooleanField(default=True, verbose_name='Опубликовать')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

blog/views.py
from django.shortcuts import render
from django.views.generic import DetailView

from blog.models import Article

def blog(request):
    context = {
        'object_list': Article.objects.all(),
        'title': " Блог",
    }
    return render(request, 'blog/article_list.html', context)


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

blog/templates/blog/article_detail.html
{% extends 'mailing/base.html' %}
{% load static %}
{% block content %}
  <div class="col-12">
    <div class="row">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">{{ object.title }}</h3>
        </div>
        <div class="card-body">
          <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            {% if object.preview != '' %}
              <img class="card-img-top" src="/media/{{ object.preview }}" alt="Card image cap" />
            {% endif %}

            <p>{{ object.body }}</p>
            <p>Дата публикации: {{ object.date_is_published }}</p>
          </ul>
          <div class="col-12">
            <div class="row">
              <div class="col-6 mt-3">
                <p>Просмотры: {{ object.views_count }}</p>
              </div>
              <div class="col-6 fmt-3">
                <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:article_list' %}">Назад к статьям</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'mailing/base.html' %}
{% block content %}
  {% if object > 0 %}
    {% with object=object_list|first %}
      <div class="jumbotron p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
        <div class="col-lg-6 px-0">
          <h1 class="display-4 fst-italic">{{ object|title }}</h1>
          <p class="lead my-3">{{ object.body|slice:150 }}...</p>
          <p class="lead mb-0">
            <a class="text-body-emphasis fw-bold" href="{% url 'blog:article_view' object.pk %}" role="button">Подробнее...</a>
          </p>
        </div>
        {% if object.preview %}
          <div class="col-auto d-none d-lg-block">
            <img class="bd-placeholder-img" width="200" height="250" src="/media/{{ object.preview }}" focusable="false" alt="Placeholder" />
          </div>
        {% endif %}
      </div>
    {% endwith %}
  {% endif %}
  <div class="row mb-2">
    {% for object in object_list %}
      <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
            <h3 class="mb-1">{{ object|title|slice:30 }}</h3>
            <div class="mb-1 text-body-secondary">{{ object.date_is_published|date:'d M Y' }}</div>
            <p class="card-text mb-auto">{{ object.body|slice:100 }}...</p>
            <a class="icon-link gap-1 icon-link-hover stretched-link" href="{% url 'blog:article_view' object.pk %}" role="button">Подробнее &raquo;</a>
          </div>
          {% if object.preview %}
            <div class="col-auto d-none d-lg-block">
              <img class="bd-placeholder-img" width="200" height="250" src="/media/{{ object.preview }}" focusable="false" alt="Placeholder" />
            </div>
          {% else %}
            <div class="col-auto d-none d-lg-block">
              <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                <title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect>
                <text x="50%" y="50%" fill="#eceeef" dy=".3em">Image not found</text>
              </svg>
            </div>
          {% endif %}
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}