blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import blog, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('article/', blog, name='article_list'),
    path('article_view/<int:pk>/', cache_page(60)(ArticleDetailView.as_view()), name='article_view'),
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users import views

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/genpassword', views.generate_new_password, name='generate_new_password'),
    path('verify/', views.activate_user),
    path('user_list/', views.get_users_list, name='list_view'),
    path('activity/<int:pk>/', views.toogle_activity, name='toogle_activity'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

NULLABLE = {'blank': True, 'null':True}

class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Почта')
    phone = models.CharField(max_length=35, verbose_name='Номер телефона', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    country = models.CharField(max_length=150, verbose_name='Страна', **NULLABLE)
    token = models.CharField(max_length=10, verbose_name='Токен верификации', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'
        permissions = [
            ("set_is_active", "Активация пользователя")
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User

class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.core.mail import send_mail
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User
from users.utils import get_new_password

class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        new_user = form.save()
        new_user.is_active = False
        secret_token = ''.join([str(random.randint(0, 9)) for string in range(10)])
        new_user.token = secret_token
        message = f'Вы указали этот E-mail в качестве основного адреса на нашей платформе!\nДля подтверждения вашего Е-mail перейдите по ссылке http://127.0.0.1:8000/users/verify/?token={secret_token}'
        send_mail(
            subject='Подтверждение E-mail адреса',
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )
        return super().form_valid(form)


def activate_user(request):
    key = request.GET.get('token')
    current_user = User.objects.filter(is_active=False)
    for user in current_user:
        if str(user.token) == str(key):
            user.is_active = True
            user.token = None
            user.save()
    response = redirect(reverse_lazy('users:login'))
    return response


def generate_new_password(request):
    new_password = get_new_password()
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()

    return redirect(reverse('users:login'))


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):  # тем самым уходим от привязки с pk
        return self.request.user


@login_required
@permission_required(['users.view_user', 'users.set_is_active'])
def get_users_list(request):
    users_list = User.objects.all()
    context = {
        'object_list': users_list,
        'title': 'Список пользователей сервиса',
    }
    return render(request, 'users/user_list.html', context)


def toogle_activity(request, pk):
    user_item = get_object_or_404(User, pk=pk)
    if user_item.is_active:
        user_item.is_active = False
    else:
        user_item.is_active = True
    user_item.save()
    return redirect('users:list_view')

users/templates/users/login.html
{% extends 'mailing/base.html' %}
{% block content %}
  <div class="form-signin w-100 m-auto">
    <form class="form-floating" method="post" enctype="multipart/form-data">
      <h3 class="h3 mb-3 fw-normal">Авторизация</h3>
      <div class="card-body">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-check text-start my-3">
          <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault" />
          <label class="form-check-label" for="flexCheckDefault">Запомнить меня</label>
        </div>
        <button class="btn btn-primary w-100 py-2" type="submit">Войти</button>
      </div>
    </form>
  </div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}
{% block content %}
  <div class="form-signin w-100 m-auto">
    <form method="post" enctype="multipart/form-data">
      <h3 class="h3 mb-3 fw-normal">Регистрация</h3>
      <div class="card-body">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary w-100 py-2" type="submit">Регистрация</button>
      </div>
    </form>
  </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}
{% block content %}
  <div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
      <div class="col-3"></div>
      <div class="col-6">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title text-center">Профиль пользователя</h3>
          </div>
          <div class="card-body">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Сохранить</button>
          </div>
          <div class="card-footer">
            <small class="text-body-secondary">Когда откроется страница "Вход", проверьте Свою почту и введите новый пароль из сообщения.</small>
            <br/>
            <a href="{% url 'users:generate_new_password' %}" class="btn btn-warning">Сгенерировать пароль</a>
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/base.html' %}
{% block content %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Почта</th>
        <th scope="col">Телефон</th>
        <th scope="col">Страна</th>
        <th scope="col">Роль</th>
        <th scope="col">Активность</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
        <tr>
          <td>{{ object }}</td>
          <td>{{ object.phone }}</td>
          <td>{{ object.country }}</td>
          {% if object.is_superuser %}
            <td>Администратор</td>
          {% elif object.is_staff %}
            <td>Менеджер</td>
          {% else %}
            <td>Пользователь</td>
          {% endif %}
          {% if perms.users.set_is_active and user.pk != object.pk %}
            {% if object.is_active %}
              <td>
                <a href="{% url 'users:toogle_activity'  object.pk %}" class="btn btn-warning">Деактивировать</a>
              </td>
            {% else %}
              <td>
                <a href="{% url 'users:toogle_activity' object.pk %}" class="btn btn-success">Активировать</a>
              </td>
            {% endif %}
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}